### ISSUE TITLE
Strange behavior for oA.

### ISSUE THREAD

**Issue by yuuukuma** [giovannipizzi/seekpath#54] opened 2018-11-13 01:06 UTC
Dear developers,

The returned structure of oA shows strange behavior.
Here is my orthorhombic BaTiO3.
```
Ba1 Ti1 O3 (call STRUCTURE A HERE)
1.0
0.000000 2.859776 -2.876106
0.000000 2.859776 2.876106
3.964208 0.000000 0.000000
Ba Ti O
1 1 3 
direct
-0.004309 1.004309 0.000000 Ba
0.480552 0.519448 0.500000 Ti
0.022641 0.491446 0.500000 O
0.508554 0.977359 0.500000 O
-0.487338 1.487338 0.000000 O
```
If the A structure is input, seekpath returns
```
Ba1 Ti1 O3 (call STRUCTURE B HERE)
1.0
0.000000 2.859776 -2.876106
0.000000 2.859776 2.876106
3.964208 0.000000 0.000000
Ba Ti O
1 1 3 
direct
0.0043090000    0.9956910000    0.0000000000
-0.4805520000   1.4805520000    0.5000000000
-0.5085540000   1.0226410000    0.5000000000
-0.0226410000   1.5085540000    0.5000000000
0.4873380000    0.5126620000    0.0000000000
```

A strange to me is when A is input, B is returned, and when B is input, A is returned.
That means the seekpath shows cyclic behavior.
Of course, these two shows the same result, so this is not a true bug in principle.
However, if possible, I would like to have a unique structure.

What do you think?

**Comment by giovannipizzi** [comment] 2018-12-19 18:02
Thanks, I'm looking into this - it might take a few weeks to fix as I'm a bit busy with some deadlines! Anyway I could reproduce the problem with the script that I paste below for (my) future reference when I'll check into this:
```python
from __future__ import print_function

import seekpath
import spglib

cell = [
    [0.000000, 2.859776, -2.876106],
    [0.000000, 2.859776, 2.876106],
    [3.964208, 0.000000, 0.000000]]

positions = [
    [-0.004309, 1.004309, 0.000000], # Ba
    [0.480552, 0.519448, 0.500000], # Ti
    [0.022641, 0.491446, 0.500000], # O
    [0.508554, 0.977359, 0.500000], # O
    [-0.487338, 1.487338, 0.000000]] # O

# Ba, Ti, O, O, O
numbers = [56, 22, 8, 8, 8]

start_structure = ((cell, positions, numbers))

#res1_spg = spglib.get_symmetry_dataset(start_structure)
#print((res1_spg['std_lattice'], res1_spg['std_positions'], res1_spg['std_types']))
res1 = seekpath.get_path(start_structure)

intermediate1_structure = (
    res1['primitive_lattice'],
    res1['primitive_positions'],
    res1['primitive_types'],
    )

print(intermediate1_structure)

print()

#res2_spg = spglib.get_symmetry_dataset(intermediate1_structure)
#print((res2_spg['std_lattice'], res2_spg['std_positions'], res2_spg['std_types']))
res2 = seekpath.get_path(intermediate1_structure)

intermediate2_structure = (
    res2['primitive_lattice'],
    res2['primitive_positions'],
    res2['primitive_types'],
    )

print(intermediate2_structure)
```

**Comment by giovannipizzi** [comment] 2019-07-25 06:54
Sorry for the long delay. I thought a bit better about it. I'm not sure it's so easy, because it's just one of the two possibilities by reflection, and the cell remains the same, only atom positions get reflected.

Actually, I tracked down this to spglib, here is a similar snippet to the one above, only using spglib and not seekpath:
```python
from __future__ import print_function

import spglib

# Original structure
cell = [
    [0.000000, 2.859776, -2.876106],
    [0.000000, 2.859776, 2.876106],
    [3.964208, 0.000000, 0.000000]]

positions = [
    [-0.004309, 1.004309, 0.000000], # Ba
    [0.480552, 0.519448, 0.500000], # Ti
    [0.022641, 0.491446, 0.500000], # O
    [0.508554, 0.977359, 0.500000], # O
    [-0.487338, 1.487338, 0.000000]] # O

# Ba, Ti, O, O, O
numbers = [56, 22, 8, 8, 8]

start_structure = ((cell, positions, numbers))

#####################################################
# First iteration
res1 = spglib.get_symmetry_dataset(start_structure)
intermediate1_structure = (
    res1['std_lattice'],
    res1['std_positions'],
    res1['std_types'],
    )
print("Spacegroup: {}".format(res1['international']))
print("First iteration: ", res1['std_positions'][0]) # Get coordinates of first atom


#####################################################
# Second iteration
res2 = spglib.get_symmetry_dataset(intermediate1_structure)
intermediate2_structure = (
    res2['std_lattice'],
    res2['std_positions'],
    res2['std_types'],
    )
print("Second iteration:", res2['std_positions'][0])

#####################################################
# Third iteration
res3 = spglib.get_symmetry_dataset(intermediate2_structure)
print("Third iteration: ", res3['std_positions'][0])
```
The output is (spglib 1.13.0):
```
Spacegroup: Amm2
First iteration:  [0.       0.5      0.495691]
Second iteration: [0.       0.5      0.504309]
Third iteration:  [0.       0.5      0.495691]
```
Showing the same cyclic behaviour.

I'm going to ask also in this case to @atztogo if he has an idea if this is something simple to fix or not. What do you think @atztogo?

**Comment by atztogo** [comment] 2019-07-25 07:34
I agree this issue is originated from spglib. But for me, this is not strange.

If we want to avoid ciclic behaviour, probably what I have to do is to fix transformation matrix to be identity in the second run. See,

```
Spacegroup: Amm2
First iteration:  [0.       0.5      0.495691]
Transformation matrix
[[ 0.   0.  -1. ]
 [ 0.5  0.5  0. ]
 [ 0.5 -0.5  0. ]]
Second iteration: [0.       0.5      0.504309]
Transformation matrix
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
Third iteration:  [0.       0.5      0.495691]
Transformation matrix
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
```

I don't find quickly a good strategy to solve this issue. I should get a permanent position to concentrate on spglib :)

**Comment by giovannipizzi** [comment] 2019-07-25 08:51
Thanks @atztogo for the quick answer, and good luck with your search of a permanent position!
Considering that this is something that should be dealt with in spglib, that it's not easy to fix and that the results are anyway correct, I'm going to close this issue

**Comment by atztogo** [comment] 2019-07-28 07:29
@giovannipizzi, I could not stop thinking about this issue, though I should stop. Finally I think I found the solution. It's tough; for [lattice systems](https://en.wikipedia.org/wiki/Crystal_system), each by each treatment is necessary. I have done the treatment for orthorhombic, monoclinic, and cubic, and it seems working. It's a painful job, but hope I will finish this job someday soon.

@yuuukuma, my treatment will not provide any perfect solution, but just stopping cycling behaviour. Crystals have degrees of freedom of generators up to affine normalizer (you should study  International Tables for Crystallography (2016). Vol. A, ch. 3.5, pp. 826-851) that will not change their space group types. If all people understand this crystallographic fact, then somebody may provide a good solution. But often, people just suggest issues without understand this fact since it looks like trivial issue. But often not, for example, in this issue case, for only stopping the cycling behaviour, I put a lot fo my effort. Spglib does a lot of painful work behind it without being known by users.

**Comment by yuuukuma** [comment] 2019-07-28 10:54
@giovannipizzi @atztogo I really appreciate both of your answers and your patient works to develop codes that contribute to the community a lot. And, sorry to post it without knowing how it's difficult. I should study more about crystallography.

**Comment by atztogo** [comment] 2019-07-30 07:02
I have released spglib v1.14.1. It's not perfect. Please have a look at the [ChangeLog](https://github.com/atztogo/spglib/blob/master/ChangeLog).

**Comment by giovannipizzi** [comment] 2019-07-30 07:28
Thanks @atztogo, I really appreciate your hard work on this! I hope you didn't get crazy on this issue :-)
I'll reopen this and (unfortunately not immediately) I'll make a new release using the newer version of spglib (task for me: make a new release with `spglib>=1.14.1`

**Comment by yuuukuma** [comment] 2019-07-30 08:26
Dear @atztogo , thanks for the update. 
I tested @giovannipizzi 's example, and found the update works well as follows,

`
Spacegroup: Amm2
First iteration:  [0.       0.5      0.495691]
Second iteration: [0.       0.5      0.495691]
Third iteration:  [0.       0.5      0.495691]
`

I will test the modified seekpath after @giovannipizzi incorporates the change.

**Comment by giovannipizzi** [comment] 2019-07-30 09:39
Unfortunately, even if now SPGLIB is stable for cyclic behaviour, the behavior comes back if in between we pass the primitive cell rather than the conventional cell (primitive cell computed by seekpath). Thanks again @atztogo but unfortunately I don't have a good idea on how to fix this, so I will put this back in a 'wontfix' state unless someone has a good suggestion on how to do this (but since this is not really a bug, I don't think it' critical). 
Anyway I will release 1.9.2 with the new dependency on spglib.

**Closed by giovannipizzi** 2019-07-30 09:39 UTC
Labels: enhancement

**Comment by atztogo** [comment] 2019-07-31 03:10
Let's discuss the issue on the seekpath side in the future but not now. What is difficult is to control the behaviour to create conventional unit cell from primitive cell. So probably to handle primitive is less difficult.
