### ISSUE TITLE
How to remap the result from seekpath to the non-standardized cell.

### ISSUE THREAD

**Issue by DeqiTang** [giovannipizzi/seekpath#77] opened 2020-03-06 16:11 UTC
Hello, guys! I am trying to implement automatical generation of k path via seekpath to https://gitlab.com/DeqiTang/pymatflow. However, the high symmetry k path generated only works for the standardized crystal structure. Any hints on remap it to non-standadized cell?

**Comment by giovannipizzi** [comment] 2020-03-10 08:59
Unfortunately, this is complex. Some partial work could be done (I refer to #16 for this).
Some comments in the readme in this branch: https://github.com/giovannipizzi/seekpath/tree/fix_transformation_matrix#id4
In particular, on the fact that the safe approach is to standardise before doing any ab initio calculation (and also at the end of a relax, before doing a final SCF).

There is also paragraph 3.3 in the same file, with some comments of what I was trying to implement (but I didn't have the time to implement it properly yet - mostly the case of triclinic symmetry that requires a specific treatment).

**Comment by DeqiTang** [comment] 2020-03-11 08:14
Well, I might first try the standardized cell. Thanks for the information! Good luck with this fantastic program!

**Comment by giovannipizzi** [comment] 2020-05-15 06:35
I'm going to close this as a duplicate of #16 - in case we can continue discussion in that issue

**Closed by giovannipizzi** 2020-05-15 06:35 UTC
